
arm_controller:
    allow_partial_joints_goal: True
    type: position_controllers/JointTrajectoryController
    joints:
       - J1
       - J2
       - J3
       - J4
       - J5
       - J6
       - GR1
       - GR2
       - GR3
       - GL1
       - GL2
       - GL3
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      hip: {trajectory: 0.1, goal: 0.1}
      shoulder: {trajectory: 0.1, goal: 0.1}
      elbow: {trajectory: 0.1, goal: 0.1}
      wrist: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

